### ISSUE TITLE
Support restarting service or sending signal after config updates

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io-roadmap#72]
Support a new property in the tedge-configuration-plugin.toml file which allows the user to either restart a service, or send a signal to a service/process to trigger the related process to re-read its configuration:

For example, if to reload the mosquitto settings, the `service` and `signal` properties could be added which will send the mosquitto service a `SIGHUP` after a configuration has been applied.

```toml
[[files]]
path = "/etc/tedge/mosquitto-conf/tedge-mosquitto.conf"
type = "tedge-mosquitto.conf"
service = "mosquitto"
signal = "SIGHUP"
```
